### ISSUE TITLE
Maximum Call Stack Size Exceeded while parsing custom grammar

### ISSUE THREAD

**Issue by fabianfreyer** [lys-lang/node-ebnf#10]
For a more complicated EBNF grammar (can't share at the moment, unfortunately), parsing the grammar fails with:

```
/home/user/service-xsharp/service/node_modules/ebnf/dist/Parser.js:53
        name: name.replace(decorationRE, '').replace(preDecorationRE, ''),
                   ^

RangeError: Maximum call stack size exceeded
    at String.replace (<anonymous>)
    at parseRuleName (/home/user/service-xsharp/service/node_modules/ebnf/dist/Parser.js:53:20)
    at options.forEach.phases (/home/user/service-xsharp/service/node_modules/ebnf/dist/Parser.js:256:47)
    at Array.forEach (<anonymous>)
    at Parser.parse (/home/user/service-xsharp/service/node_modules/ebnf/dist/Parser.js:233:25)
    at options.forEach.phases (/home/user/service-xsharp/service/node_modules/ebnf/dist/Parser.js:282:51)
    at Array.forEach (<anonymous>)
    at Parser.parse (/home/user/service-xsharp/service/node_modules/ebnf/dist/Parser.js:233:25)
    at options.forEach.phases (/home/user/service-xsharp/service/node_modules/ebnf/dist/Parser.js:282:51)
    at Array.forEach (<anonymous>)
```

**Comment by menduz** [comment]
In this case we have an invalid state machine for the parser, but the error isn't happy at all.

`RValue -> InfixExpression -> RValue -> InfixExpression -> RValue -> InfixExpression ...`

That is called `left recursion` in parsers, and this generator doesn't support it.

Though, you can reconfigure your grammar:

```
{ ws=explicit }

InfixExpression ::= RValue (InfixOperator RValue)* {simplifyWhenOneChildren=true}
RValue ::= Number WS*
InfixOperator ::= WS* ("+" | "-" | "*" | "/") WS*
Number ::= "-"? ("0" | [1-9] [0-9]*) ("." [0-9]+)? (("e" | "E") ( "-" | "+" )? ("0" | [1-9] [0-9]*))?

WS ::= ' '

```
